### PR TITLE
Add managed disks

### PR DESCRIPTION
**Pull request by petems**
Continued from https://github.com/terraform-providers/terraform-provider-azurestack/pull/52

Adds the vendor changes as requested 👍

### CODE REVIEW

**Comment by petems** [comment]
Currently blocked on waiting for azure profiles to be updated: https://github.com/Azure/azure-sdk-for-go/issues/3373#issuecomment-475176266

Requires `2018-08`, currently only `2018-03` exists

**Comment by martinbjorgan** [comment]
Managed disk support is available in 2018-03-01-hybrid profile

**Comment by petems** [comment]
Yep, `2018-03-01-hybrid` is due early April according to [this comment ](https://github.com/Azure/azure-sdk-for-go/issues/3373#issuecomment-475700738)

**Comment by katbyte** [comment]
@petems, i think the comment mentioned the `2018-03-01-hybrid` profile was released last august.

**Comment by petems** [comment]
> So the managed disk support is available in 2018-03-01-hybrid profile itself. 2019-03-01-hybrid profile is in the works and we expect that to be released by May first week.

**Comment by katbyte** [comment]
@petems,

I am about to upgrade the SDK to v29 (#83) and have created #84 with the newest profile that should contain manage disk support. You should be able to rebase off that branch and get it all workthing now 🙂

**Pull request closed without merging**
